#!/usr/bin/env ruby
# This command will push a new secret token to Heroku. 


def random_alphanum(size)
  chars = (('a'..'z').to_a + ('0'..'9').to_a) - %w(i o 0 1 l 0)
  (1..size).collect{|a| chars[rand(chars.size)] }.join
end    

# Note if you are running this on another host, you will need to manually 
# set the environment variable BPS_SECRET_TOKEN, or change the code 
# in ./config/initializers/secret_token.rb
puts "Generating a new secret token on heroku..."
puts `heroku config:add BPS_SECRET_TOKEN=#{random_alphanum(128)}`
puts "Heroku secret token successfully updated"
